# Generated by Django 4.2.3 on 2023-08-25 14:28

from django.db import migrations, models


def create_default_user(apps, schema):
    User = apps.get_model("auth", "User")
    User.objects.create(username="La Femme", is_active=True)


def create_dsp(apps, schema):
    DSP = apps.get_model("distribution", "DSP")
    DSP.objects.bulk_create(
        [
            DSP(name="spotify"),
            DSP(name="deezer"),
            DSP(name="apple"),
            DSP(name="youtube"),
        ]
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DSP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RunPython(
            create_default_user,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_dsp,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
